#!/bin/bash

# Do not publish docs for pull requests
if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then
	echo "Building docs only for commits on master branch!"
	exit 0
fi
if [[ "$TRAVIS_JOB_NUMBER" != *.1 ]]; then
	echo "Building docs only for first Travis job!"
	exit 0
fi

DOCS_BUILD="docs"
DOCS_REPO="tmp"

rm -rf $DOCS_BUILD $DOCS_REPO

# clone the gh-pages branch
git clone -v --branch gh-pages https://github.com/avaly/wurfl-cloud-client.git $DOCS_REPO

# generate the docs
node_modules/.bin/yuidoc
cd $DOCS_BUILD
rsync -rt --exclude=".git" . $DOCS_REPO
cd ..

# setup git credentials in gh-pages repository
cd $DOCS_REPO
git config credential.helper "store --file=.git/credentials"
echo "https://$GH_TOKEN:@github.com" > .git/credentials
git config --global user.name "Travis CI"
git config --global user.email "travis@travis-ci.com"

# commit & push docs
git add --all .
git commit -m "Documentation update for $TRAVIS_COMMIT"
git push origin gh-pages
